### ISSUE TITLE
Error: keyerror when get response from baidu server

### ISSUE THREAD

**Issue by kmahyyg** [Jiangtaste/weixin.qingsonge.com#1]
https://github.com/kmahyyg/dissADtel/issues/2

**Comment by kmahyyg** [comment]
Thanks for your hard work. 
Same ID in V2EX.

**Comment by kmahyyg** [comment]
Traceback log: https://sentry.io/share/issue/4ca13cf8723f4d47ba832b12ea6a2d64/

**Comment by jiangtaste** [comment]
问题排查：
1. 目前start_call()中未对电话号码再次做验证，可能是传入的phone不正确
2. start_call()执行后，使用request的json()获取响应内容时会存在诡异问题（我也还未摸明白request库）

**Comment by kmahyyg** [comment]
1. 传入phone没问题

**Comment by kmahyyg** [comment]
一点小小建议， 不要用 ``` %s % VAR ```来格式化字符串， 那是Python2.7的语法。 Python3请使用format方法和 template.

**Comment by kmahyyg** [comment]
debug :  '{"status":252,"msg":"非法请求，呼叫失败。"}'
